import { Check, MapPin, Newspaper, Phone, SkipForward, UserRound, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import StatusBadge from '../common/StatusBadge';

const statuses = [['DELIVERED', 'Delivered', Check], ['NOT_DELIVERED', 'Not delivered', X], ['SKIPPED', 'Skipped', SkipForward]];

export default function DeliveryCard({ delivery, isUpdating, onStatusChange }) {
  return <article className="rounded-2xl border border-[#e6e1dd] bg-white p-5 shadow-[0_8px_24px_rgba(29,27,26,0.04)]"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="truncate font-display text-lg font-bold">{delivery.customerName}</h2><StatusBadge tone={delivery.status === 'DELIVERED' ? 'success' : delivery.status === 'SKIPPED' ? 'warning' : 'danger'}>{delivery.status}</StatusBadge></div><p className="mt-2 flex items-start gap-2 text-sm text-[#706a65]"><MapPin size={16} className="mt-0.5 shrink-0" /> {delivery.customerAddress}</p></div>{delivery.customerId && <Link className="text-xs font-semibold text-[#b42318] hover:underline" to={`/customers/${delivery.customerId}`}>Customer</Link>}</div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><Info icon={Newspaper} label="Newspaper" value={`${delivery.newspaperName} · ${delivery.copiesDelivered} copies`} /><Info icon={Phone} label="Delivery date" value={delivery.deliveryDate} /><Info icon={UserRound} label="Route" value={`${delivery.beatName}${delivery.paperBoyName ? ` · ${delivery.paperBoyName}` : ''}`} /></div><div className="mt-5 flex flex-wrap gap-2">{statuses.map(([value, label, Icon]) => <button key={value} type="button" disabled={isUpdating || delivery.status === value} onClick={() => onStatusChange(value)} className={`inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-xs font-semibold ring-1 transition ${delivery.status === value ? 'bg-[#f2efec] text-[#8d8782] ring-[#e6e1dd]' : 'bg-white text-[#605b57] ring-[#ded9d4] hover:bg-[#fff0ee] hover:text-[#b42318]'}`}><Icon size={15} /> {label}</button>)}</div></article>;
}

function Info({ icon: Icon, label, value }) { return <div className="flex items-start gap-2"><Icon size={16} className="mt-0.5 shrink-0 text-[#8d8782]" /><div><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-[#8d8782]">{label}</p><p className="mt-1 text-[#383331]">{value}</p></div></div>; }