import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import Button from '../common/Button';
import AuthField from '../auth/AuthField';

const methods = [['CASH', 'Cash'], ['UPI', 'UPI'], ['BANK_TRANSFER', 'Bank Transfer'], ['OTHER', 'Other']];

export default function PaymentForm({ bill, isSubmitting, serverError, onSubmit }) {
  const { register, handleSubmit, setError, formState: { errors } } = useForm({ defaultValues: { amount: '', paymentMethod: '', transactionRef: '', notes: '' } });
  useEffect(() => { if (serverError?.fieldErrors) Object.entries(serverError.fieldErrors).forEach(([field, message]) => setError(field, { type: 'server', message })); }, [serverError, setError]);
  const submit = (values) => onSubmit({ billId: bill.id, amount: Number(values.amount), paymentMethod: values.paymentMethod, ...(values.transactionRef ? { transactionRef: values.transactionRef } : {}), ...(values.notes ? { notes: values.notes } : {}) });
  const due = Number(bill.dueAmount || 0);
  return <form className="space-y-5" onSubmit={handleSubmit(submit)} noValidate><div className="rounded-2xl bg-[#1d1b1a] p-5 text-white"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#fca5a1]">Current due</p><p className="mt-2 font-display text-4xl font-bold">₹{due.toFixed(2)}</p></div><AuthField label="Amount" type="number" min="0.01" max={due} step="0.01" placeholder="0.00" error={errors.amount?.message} {...register('amount', { required: 'Payment amount is required', validate: (value) => Number(value) > 0 || 'Payment amount must be greater than zero', max: { value: due, message: `Payment amount cannot exceed the current due amount of ₹${due.toFixed(2)}` } })} /><label className="block"><span className="mb-2 block text-sm font-semibold text-[#383331]">Payment method</span><select className={`min-h-12 w-full rounded-xl bg-white px-4 text-sm outline-none ring-1 ${errors.paymentMethod ? 'ring-[#d92d20]' : 'ring-[#ded9d4]'}`} {...register('paymentMethod', { required: 'Payment method is required' })}><option value="">Select a payment method</option>{methods.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>{errors.paymentMethod && <span className="mt-1.5 block text-xs font-medium text-[#b42318]">{errors.paymentMethod.message}</span>}</label><AuthField label="Transaction reference" placeholder="Optional" error={errors.transactionRef?.message} {...register('transactionRef')} /><label className="block"><span className="mb-2 block text-sm font-semibold text-[#383331]">Notes</span><textarea className="min-h-24 w-full rounded-xl bg-white px-4 py-3 text-sm outline-none ring-1 ring-[#ded9d4]" placeholder="Optional" {...register('notes')} /></label>{serverError?.message && !Object.keys(serverError.fieldErrors || {}).length && <p className="rounded-xl bg-[#fff0ee] px-4 py-3 text-sm font-medium text-[#b42318]">{serverError.message}</p>}<Button type="submit" disabled={isSubmitting || due <= 0}>{isSubmitting ? 'Recording payment...' : due <= 0 ? 'No payment due' : 'Record payment'}</Button></form>;
}