import { useEffect } from 'react';
import { useForm, useWatch } from 'react-hook-form';
import Button from '../common/Button';
import AuthField from '../auth/AuthField';
import ScheduleSelector from './ScheduleSelector';

const defaultSchedule = { monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, saturday: true, sunday: true };
const emptyValues = { customerId: '', newspaperId: '', copies: 1, pricePerCopy: '', startDate: '', endDate: '', deliverySchedule: defaultSchedule };

export default function SubscriptionForm({ initialValues = emptyValues, customers, newspapers, isSubmitting, serverError, onSubmit, submitLabel, lockedCustomerId }) {
  const { register, reset, handleSubmit, setError, control, formState: { errors } } = useForm({ defaultValues: initialValues });
  const schedule = useWatch({ control, name: 'deliverySchedule', defaultValue: initialValues.deliverySchedule || defaultSchedule });
  useEffect(() => { reset({ ...emptyValues, ...initialValues, customerId: initialValues.customerId ? String(initialValues.customerId) : '', newspaperId: initialValues.newspaperId ? String(initialValues.newspaperId) : '', deliverySchedule: { ...defaultSchedule, ...(initialValues.deliverySchedule || {}) } }); }, [initialValues, reset]);
  useEffect(() => { if (serverError?.fieldErrors) Object.entries(serverError.fieldErrors).forEach(([field, message]) => setError(field, { type: 'server', message })); }, [serverError, setError]);
  const submit = (values) => onSubmit({ customerId: Number(values.customerId), newspaperId: Number(values.newspaperId), copies: Number(values.copies), pricePerCopy: values.pricePerCopy === '' ? null : Number(values.pricePerCopy), startDate: values.startDate, endDate: values.endDate || null, deliverySchedule: values.deliverySchedule });
  return <form className="space-y-5" onSubmit={handleSubmit(submit)} noValidate><div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-sm font-semibold text-[#383331]">Customer</span><select disabled={Boolean(lockedCustomerId)} className={`min-h-12 w-full rounded-xl bg-white px-4 text-sm outline-none ring-1 ${errors.customerId ? 'ring-[#d92d20]' : 'ring-[#ded9d4]'}`} {...register('customerId', { required: 'Customer ID is required' })}><option value="">Select a customer</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select>{errors.customerId && <span className="mt-1.5 block text-xs font-medium text-[#b42318]">{errors.customerId.message}</span>}</label><label className="block"><span className="mb-2 block text-sm font-semibold text-[#383331]">Newspaper</span><select className={`min-h-12 w-full rounded-xl bg-white px-4 text-sm outline-none ring-1 ${errors.newspaperId ? 'ring-[#d92d20]' : 'ring-[#ded9d4]'}`} {...register('newspaperId', { required: 'Newspaper ID is required' })}><option value="">Select a newspaper</option>{newspapers.map((newspaper) => <option key={newspaper.id} value={newspaper.id}>{newspaper.name}</option>)}</select>{errors.newspaperId && <span className="mt-1.5 block text-xs font-medium text-[#b42318]">{errors.newspaperId.message}</span>}</label><AuthField label="Copies" type="number" min="1" error={errors.copies?.message} {...register('copies', { required: 'Copies count is required', min: { value: 1, message: 'Copies must be at least 1' }, valueAsNumber: true })} /><AuthField label="Price per copy" type="number" min="0.01" step="0.01" placeholder="Optional" error={errors.pricePerCopy?.message} {...register('pricePerCopy', { min: { value: 0.01, message: 'Price must be greater than zero' }, valueAsNumber: false })} /><AuthField label="Start date" type="date" error={errors.startDate?.message} {...register('startDate', { required: 'Start date is required' })} /><AuthField label="End date" type="date" error={errors.endDate?.message} {...register('endDate')} /></div><ScheduleSelector register={register} values={schedule || defaultSchedule} />{(serverError?.message && !Object.keys(serverError.fieldErrors || {}).length) && <p className="rounded-xl bg-[#fff0ee] px-4 py-3 text-sm font-medium text-[#b42318]">{serverError.message}</p>}<Button type="submit" disabled={isSubmitting}>{isSubmitting ? 'Saving subscription...' : submitLabel}</Button></form>;
}