import { ArrowLeft, Check, Edit3, FileText, MapPin, Phone, Repeat2, ShieldCheck, UserRound, X } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import PageHeader from '../../components/layout/PageHeader';
import StatusBadge from '../../components/common/StatusBadge';
import Button from '../../components/common/Button';
import { ErrorState, LoadingState } from '../../components/common/StateViews';
import { useCustomer, useCustomerMutations } from '../../queries/customerQueries';

export default function CustomerDetailPage() {
  const { customerId } = useParams();
  const navigate = useNavigate();
  const query = useCustomer(customerId);
  const { patchStatus } = useCustomerMutations();
  if (query.isLoading) return <LoadingState label="Loading customer profile" />;
  if (query.isError) return <div className="space-y-6"><BackLink /><ErrorState message={query.error.status === 404 ? 'Customer not found.' : query.error.message} onRetry={query.refetch} /></div>;
  const customer = query.data;
  const patch = (changes) => patchStatus.mutate({ id: customer.id, changes });
  const toggleActive = () => { if (customer.active && !window.confirm('Deactivate this customer? This changes active state; it does not delete the customer.')) return; patch({ active: !customer.active }); };
  return <div className="space-y-8"><BackLink /><PageHeader eyebrow="Customer profile" title={customer.name} description={customer.notes || 'Customer information returned by the backend.'} action={<StatusBadge tone={customer.active ? 'success' : 'neutral'}>{customer.active ? 'Active' : 'Inactive'}</StatusBadge>} /><section className="grid gap-4 md:grid-cols-2"><InfoCard icon={Phone} label="Contact" value={customer.mobileNumber} extra={customer.alternateMobile ? `Alternate: ${customer.alternateMobile}` : null} /><InfoCard icon={MapPin} label="Address" value={customer.address} extra={customer.beatName ? `Beat: ${customer.beatName}` : null} /><InfoCard icon={ShieldCheck} label="WhatsApp" value={customer.whatsAppEnabled ? 'Enabled' : 'Disabled'} extra="Notification preference only" /><InfoCard icon={UserRound} label="Paper boy" value={customer.paperBoyName || 'Not assigned'} extra={customer.paperBoyId ? `ID: ${customer.paperBoyId}` : null} /></section><section className="grid gap-4 sm:grid-cols-3"><Metric label="Bill status" value={customer.billStatus || 'Not available'} /><Metric label="Current bill amount" value={formatAmount(customer.currentBillAmount)} /><Metric label="Due amount" value={formatAmount(customer.dueAmount)} /></section><section className="grid gap-4 md:grid-cols-2"><RelatedSection icon={Repeat2} title="Subscriptions" detail={`${customer.activeSubscriptionsCount} active subscription${customer.activeSubscriptionsCount === 1 ? '' : 's'} reported by the customer profile.`} viewHref={`/customers/${customer.id}/subscriptions`} addHref={`/customers/${customer.id}/subscriptions/new`} viewLabel="View subscriptions" addLabel="Add subscription" /><RelatedSection icon={FileText} title="Bills" detail="View bills returned for this customer." viewHref={`/customers/${customer.id}/bills`} addHref={`/customers/${customer.id}/bills/generate`} viewLabel="View bills" addLabel="Generate bill" /></section><section className="flex flex-wrap gap-3"><Link to={`/customers/${customer.id}/edit`}><Button variant="secondary"><Edit3 size={16} /> Edit customer</Button></Link><Button variant="secondary" onClick={toggleActive} disabled={patchStatus.isPending}>{customer.active ? 'Deactivate customer' : 'Activate customer'}</Button><Button variant="secondary" onClick={() => patch({ whatsAppEnabled: !customer.whatsAppEnabled })} disabled={patchStatus.isPending}>{customer.whatsAppEnabled ? <><X size={16} /> Disable WhatsApp</> : <><Check size={16} /> Enable WhatsApp</>}</Button></section>{patchStatus.isError && <ErrorState message={patchStatus.error.message} onRetry={() => patchStatus.reset()} />}<p className="text-xs text-[#8d8782]">Customer billing and subscription status are kept synchronized with the backend.</p></div>;
  function BackLink() { return <Link className="inline-flex items-center gap-2 text-sm font-semibold text-[#706a65] hover:text-[#b42318]" to="/customers"><ArrowLeft size={17} /> Back to customers</Link>; }
}

function InfoCard({ icon: Icon, label, value, extra }) { return <div className="rounded-2xl border border-[#e6e1dd] bg-white p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#f2efec] text-[#706a65]"><Icon size={18} /></span><p className="mt-5 text-xs font-bold uppercase tracking-[0.12em] text-[#8d8782]">{label}</p><p className="mt-2 font-semibold text-[#272321]">{value}</p>{extra && <p className="mt-1 text-sm text-[#706a65]">{extra}</p>}</div>; }
function RelatedSection({ icon: Icon, title, detail, viewHref, addHref, viewLabel, addLabel }) { return <section className="rounded-2xl border border-[#e6e1dd] bg-white p-5"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#fff0ee] text-[#d92d20]"><Icon size={18} /></span><div><h2 className="font-display text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-[#706a65]">{detail}</p></div></div><div className="mt-5 flex flex-wrap gap-3"><Link className="text-sm font-semibold text-[#b42318] hover:underline" to={viewHref}>{viewLabel}</Link><Link className="text-sm font-semibold text-[#b42318] hover:underline" to={addHref}>{addLabel}</Link></div></section>; }
function Metric({ label, value }) { return <div className="rounded-2xl border border-[#e6e1dd] bg-white p-5"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#8d8782]">{label}</p><p className="mt-3 break-words font-display text-2xl font-bold text-[#1d1b1a]">{value}</p></div>; }
function formatAmount(value) { return value === null || value === undefined ? 'Not available' : `₹${Number(value).toFixed(2)}`; }