import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import Button from '../common/Button';
import AuthField from '../auth/AuthField';

const emptyValues = { name: '', mobileNumber: '', alternateMobile: '', address: '', beatId: '', paperBoyId: '', notes: '', whatsAppEnabled: true };

export default function CustomerForm({ initialValues = emptyValues, beats = [], paperBoys = [], isSubmitting, serverError, onSubmit, submitLabel }) {
  const { register, reset, handleSubmit, setError, formState: { errors } } = useForm({ defaultValues: initialValues });
  useEffect(() => { reset({ ...emptyValues, ...initialValues, beatId: initialValues.beatId ? String(initialValues.beatId) : '', paperBoyId: initialValues.paperBoyId ? String(initialValues.paperBoyId) : '' }); }, [initialValues, reset]);
  useEffect(() => { if (serverError?.fieldErrors) Object.entries(serverError.fieldErrors).forEach(([field, message]) => setError(field, { type: 'server', message })); }, [serverError, setError]);
  const submit = (values) => onSubmit({ ...values, beatId: Number(values.beatId), paperBoyId: values.paperBoyId ? Number(values.paperBoyId) : null, whatsAppEnabled: Boolean(values.whatsAppEnabled), alternateMobile: values.alternateMobile || null, notes: values.notes || null });
  return <form className="space-y-5" onSubmit={handleSubmit(submit)} noValidate><div className="grid gap-5 sm:grid-cols-2"><AuthField label="Name" placeholder="Customer name" error={errors.name?.message} {...register('name', { required: 'Customer name is required' })} /><AuthField label="Mobile number" placeholder="9876543210" error={errors.mobileNumber?.message} {...register('mobileNumber', { required: 'Mobile number is required' })} /><AuthField label="Alternate mobile" placeholder="Optional" error={errors.alternateMobile?.message} {...register('alternateMobile')} /><label className="block"><span className="mb-2 block text-sm font-semibold text-[#383331]">Beat</span><select className={`min-h-12 w-full rounded-xl bg-white px-4 text-sm outline-none ring-1 ${errors.beatId ? 'ring-[#d92d20]' : 'ring-[#ded9d4]'}`} {...register('beatId', { required: 'Beat ID is required' })}><option value="">Select a beat</option>{beats.map((beat) => <option key={beat.id} value={beat.id}>{beat.name}</option>)}</select>{errors.beatId && <span className="mt-1.5 block text-xs font-medium text-[#b42318]">{errors.beatId.message}</span>}</label></div><label className="block"><span className="mb-2 block text-sm font-semibold text-[#383331]">Address</span><textarea className={`min-h-24 w-full rounded-xl bg-white px-4 py-3 text-sm outline-none ring-1 ${errors.address ? 'ring-[#d92d20]' : 'ring-[#ded9d4]'}`} placeholder="Customer address" {...register('address', { required: 'Address is required' })} />{errors.address && <span className="mt-1.5 block text-xs font-medium text-[#b42318]">{errors.address.message}</span>}</label><div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-sm font-semibold text-[#383331]">Paper boy</span><select className="min-h-12 w-full rounded-xl bg-white px-4 text-sm outline-none ring-1 ring-[#ded9d4]" {...register('paperBoyId')}><option value="">None / unassigned</option>{paperBoys.map((paperBoy) => <option key={paperBoy.id} value={paperBoy.id}>{paperBoy.name}</option>)}</select></label><AuthField label="Notes" placeholder="Optional" error={errors.notes?.message} {...register('notes')} /></div><label className="flex min-h-12 items-center gap-3 rounded-xl border border-[#e6e1dd] bg-white px-4 text-sm font-semibold text-[#383331]"><input type="checkbox" className="size-4 accent-[#d92d20]" {...register('whatsAppEnabled')} /> WhatsApp enabled</label>{(serverError?.message && !Object.keys(serverError.fieldErrors || {}).length) && <p className="rounded-xl bg-[#fff0ee] px-4 py-3 text-sm font-medium text-[#b42318]">{serverError.message}</p>}<Button type="submit" disabled={isSubmitting}>{isSubmitting ? 'Saving customer...' : submitLabel}</Button></form>;
}
